🐛 : use ignoring minutes instead of seconds
to correct a case when the test fails like this

Error:  Failures:
Error:    GitlabRegistryControllerIT.testImportRepository:116
Expecting:
  <2021-01-29T13:16:59.919233 (java.time.LocalDateTime)>
to have same year, month, day, hour and minute as:
  <2021-01-29T13:17:00.157461 (java.time.LocalDateTime)>
but had not.